lobby:
  world: "world"

game:
  world: "minehunt_game"
  disconnectGraceSeconds: 120
  disablePrivateChat: true

auto:
  minPlayers: 2
  countdownSeconds: 90

reset:
  postgameSendBackDelaySec: 90
  blockStartWhileResetting: true
  randomSeedEachRound: true

scatter:
  runnerRingRadius: 180
  runnerRingJitter: 24
  hunterCenterScatterRadius: 8
  maxTries: 30

world:
  preloadRadiusBlocks: 640

# 文本与多语言
messages:
  prefix: "&7[&aMineHunt&7]&r "
locale: zh_CN

compatibility:
  useExternalChat: true
  useExternalTab: true